[PyBirdmnuw0wacdm]
git-tree-sha1 = "71ce5065840f617c33f7894e863d6876607514bd"

    [[PyBirdmnuw0wacdm.download]]
    sha256 = "abc6969ebefde319f3e62f986ca37d4fcf2f4cca88e98d6a24a9ffcbc647055d"
    url = "https://zenodo.org/records/20631625/files/trained_effort_pybird_mnuw0wacdm.tar.xz"

[trained_effort_velocileptors_lpt_mnuw0wacdm]
git-tree-sha1 = "0f06fe225e201a1eff4c1b453cbda7a710b753ec"

    [[trained_effort_velocileptors_lpt_mnuw0wacdm.download]]
    sha256 = "dffbb01c5383b393788190f2a16ebf79c763ec9ee31ff78bef08a7b473127690"
    url = "https://zenodo.org/records/20631626/files/trained_effort_velocileptors_lpt_mnuw0wacdm.tar.xz"

[trained_effort_velocileptors_rept_mnuw0wacdm]
git-tree-sha1 = "9a56ffc7bc7c846ea19870f285e722855da34128"

    [[trained_effort_velocileptors_rept_mnuw0wacdm.download]]
    sha256 = "277386435d225b068ef3c35669febee03a12910a961f4507b1a2a8740d0d5fef"
    url = "https://zenodo.org/records/20631359/files/trained_effort_velocileptors_rept_mnuw0wacdm.tar.xz"
