[PyBirdmnuw0wacdm]
git-tree-sha1 = "fea7eb09ab0c17ae4eb24e96d7b480beb12df81d"

    [[PyBirdmnuw0wacdm.download]]
    sha256 = "e63dfaafe08244087ebd02382f01c896925725d573c872073d6170820acdf381"
    url = "https://zenodo.org/records/20576776/files/trained_effort_pybird_mnuw0wacdm.tar.xz"

[trained_effort_velocileptors_lpt_mnuw0wacdm]
git-tree-sha1 = "8e4748f7d908ad703a3dbc149f37ed1082c95b31"

    [[trained_effort_velocileptors_lpt_mnuw0wacdm.download]]
    sha256 = "ed01f8758f1891066820a6ced75888b511f6267af821609d276f735f4f30c8ca"
    url = "https://zenodo.org/records/20576777/files/trained_effort_velocileptors_lpt_mnuw0wacdm.tar.xz"

[trained_effort_velocileptors_rept_mnuw0wacdm]
git-tree-sha1 = "b0cf51b38905aad4bac5987e11b277fe63140f10"

    [[trained_effort_velocileptors_rept_mnuw0wacdm.download]]
    sha256 = "c4d4fac6b3adb253b22951c439a91ce0849ce9996288eaa2b66ae670d7b7c73f"
    url = "https://zenodo.org/records/20576701/files/trained_effort_velocileptors_rept_mnuw0wacdm.tar.xz"
