name: Benchmark Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.10", "1.11", "1.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Run AirspeedVelocity benchmark
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: ${{ matrix.julia-version }}
          bench-on: "head" # Benchmark only on the PR branch
          script: "benchmark/benchmarks.jl"
          extra-pkgs: "AbstractCosmologicalEmulators,DataInterpolations,FastGaussQuadrature,Integrals,LegendrePolynomials,LinearAlgebra,NPZ,OrdinaryDiffEqTsit5,Tullio,Zygote"
